---
minimum_pre_commit_version: 2.4.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--allow-multiple-documents"]

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.7.1.15
    hooks:
      - id: actionlint
        additional_dependencies:
          - shellcheck-py>=0.9.0.5
