name: Build Documentation

on:
  workflow_call:

jobs:
  Docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10 For Nox
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Nox
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - name: Install Doc Requirements
      run: |
        nox --force-color -e docs --install-only

    - name: Build Docs
      env:
        SKIP_REQUIREMENTS_INSTALL: YES
      run: |
        nox --force-color -e docs

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: html-docs
        path: docs/_build/html

    - name: Set Exit Status
      if: always()
      run: |
        mkdir exitstatus
        echo "${{ job.status }}" > exitstatus/${{ github.job }}

    - name: Upload Exit Status
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: exitstatus
        path: exitstatus
        if-no-files-found: error

  # This requires `pages: write` and `id-token: write` permissions
  Deploy-Docs-GH-Pages:
    name: Publish Docs to GitHub Pages
    needs: Docs
    if: |
      ${{ inputs.gh-pages-docs }} &&
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: html-docs
